spring:
  datasource:
#    url:  jdbc:h2:tcp://localhost/~/db/ddangn
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace

server:
  port: 8080